### ISSUE TITLE
Результат balance при успешной операции не уменьшается на amount 

### ISSUE THREAD

**Issue by Elena15414** [Elena15414/AccountBank#1]
### Описание
Результат balance при успешной операции не уменьшается на amount в методе pay в классе CreditAccount, как должно быть по условию , а balance = отрицательному значению суммы покупки .
### Локация дефекта
https://github.com/Elena15414/AccountBank/blob/3e529e80199188772a63f1f82db9f09be48039e1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46C2-L46C31
### Шаги воспроизведения

1.Открыть код программы в IDEA
2.Выставить значение переменной amount(сумма покупок) в 50 рублей
3.Запустить программу
4.Посмотреть на вывод в консоли

_Ожидаемый результат:_ При успешном выполнении метода pay , баланс должен уменьшиться на сумму покупки balance = balance - amount.
_Фактический результат :_ При успешном выполнении метода pay , баланс не уменьшиться на сумму покупки balance = balance - amount, а происходит выполнение следующих действий balance = -amount
### Скриншот
![Screenshot_1](https://github.com/Elena15414/AccountBank/assets/123021392/63cb8324-afff-4a6c-b92e-9defdc5ccda3)

### Окружение
**Операционная система:** Windows 10,64-разрядная операционная система, Intel(R) Core(TM) i5-3317U CPU @ 
**IDEA:** IntelliJ IDEA Community Edition 2023.1.2
**Java:** OpenJDK 11

**Comment by Alexandr-Kucherenko** [comment]
# Шаги по исправлению бага
* выполнение формулы **balance = balance - amount;** поставил после выполнения условия **if (balance > -creditLimit)**
*  изменил формулу **balance = - amount;** на **balance = balance - amount;**
# Скриншот
![image](https://github.com/Elena15414/AccountBank/assets/129050393/a8158900-c408-47b3-b6d3-664b33feecdb)
