### ISSUE TITLE
Баланс приравнивается сумме покупки в методе Add в классе CreditAccount при успешном вызове метода

### ISSUE THREAD

**Issue by Elena15414** [Elena15414/AccountBank#3]
### Описание
Результат balance при успешной операции в методе  Add в классе CreditAccount приравнивается сумме покупки.
### Локация дефекта
https://github.com/Elena15414/AccountBank/blob/55d34998a7b037e58c2b1d46f5bf780e3ebf1476/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69
### Шаги воспроизведения

1.Открыть код программы в IDEA , тест shouldTestAddTrue
2.Выставить значение переменной amount(сумма покупок) в 50 рублей
3.Запустить программу
4.Посмотреть на вывод в консоли

_Ожидаемый результат_: При успешном выполнении метода Add  , баланс должен увеличиться на сумму покупки balance = balance + amount, expected=55
_Фактический результат_ : При успешном выполнении метода Add  , баланс приравнивается сумме покупки balance = amount

### Скриншот
![AddTrue](https://github.com/Elena15414/AccountBank/assets/123021392/e93e8f4c-b8b7-4998-8c92-10931668a8da)

### Окружение
**Операционная система:** Windows 10,64-разрядная операционная система, Intel(R) Core(TM) i5-3317U CPU @
**IDEA:** IntelliJ IDEA Community Edition 2023.1.2
**Java:** OpenJDK 11

**Comment by Alexandr-Kucherenko** [comment]
# Шаги по исправлению бага в методе public boolean add(int amount) класса CreditAccount
* исправил формулу расчета в методе **public boolean add(int amount)** с **balance = amount;** на **balance += amount;**
# скриншот теста shouldTestAddTrue после внесения правок в метод
![image](https://github.com/Elena15414/AccountBank/assets/129050393/b0c8731e-182a-4770-ab92-629a0e7f1f7f)
