### ISSUE TITLE
Отсутствие условий для выполнения метода  yearChange в классе CreditAccount

### ISSUE THREAD

**Issue by Elena15414** [Elena15414/AccountBank#4]
### Описание
 Отсутствие условий для выполнения метода  yearChange в классе CreditAccount. 
- Операция расчёта процентов на отрицательный баланс счёта при условии, что счёт не будет меняться год.
- Если на счёте 200 рублей, то при любой ставке ответ должен быть 0.

### Локация дефекта
https://github.com/Elena15414/AccountBank/blob/55d34998a7b037e58c2b1d46f5bf780e3ebf1476/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

### Шаги воспроизведения
1.Открыть код программы в IDEA, тест shouldTestYearChange2
2.Выставить значение переменной initialBalance в 200 рублей
3.Запустить программу
4.Посмотреть на вывод в консоли

Ожидаемый результат: Выполнение условия " Если на счёте 200 рублей, то при любой ставке ответ должен быть 0"
Фактический результат : Программа рассчитывает сумму согласно формуле balance / 100 * rate 

Скриншот
![YearChange2](https://github.com/Elena15414/AccountBank/assets/123021392/061be4ec-2dca-4e94-bdf5-211a9235e474)

Окружение
Операционная система: Windows 10,64-разрядная операционная система, Intel(R) Core(TM) i5-3317U CPU @
IDEA: IntelliJ IDEA Community Edition 2023.1.2
Java: OpenJDK 11

**Comment by Alexandr-Kucherenko** [comment]
# Шаги по исправлению бага в методе public int yearChange() класса CreditAccount
* добавил в метод public int yearChange()  условие на проверку балланса, который должен быть отрицательным и не выходить за рамки отрицательного кредитного лимита:  **if (balance > -creditLimit && balance<0)**
# Скриншот теста shouldTestYearChange2
![image](https://github.com/Elena15414/AccountBank/assets/129050393/d1b94b83-9488-4f15-8590-77e62a8bdbf0)
