### ISSUE TITLE
Отсутствуют условия проверки допустимого значения баланса в методе yearChange класса SavingAccount при начислении процентов

### ISSUE THREAD

**Issue by Alexandr-Kucherenko** [Elena15414/AccountBank#5]
# Описание
Начисление процентов согласно методу происходит при сумме на счете меньше допустимого значения minbalance.
# Локация дефекта
https://github.com/Elena15414/AccountBank/blob/ad5daed532e69e64240e0d20345c3ab7580b9ac8/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L99
# Шаги воспроизведения
1.Открыть код программы в IDEA, тест shouldTestYearChange2
2.Поставить  значение переменной initialBalance 900 рублей
3.Поставить  значение переменной minBalance 1000 рублей
3.Запустить тест public void testRateWhenLessMinBalance()
4.Посмотреть на вывод в консоли

*Ожидаемый результат :* Вывод сообщения о нулевом начислении процентной ставке 
*Фактический результат :* Программа рассчитывает сумму согласно формуле balance / 100 * rate

# Скриншот
![image](https://github.com/Elena15414/AccountBank/assets/129050393/d1543dd8-efce-491a-82f3-89746e25408c)
# Окружение
* **Операционная система :** Mozilla/5.0 (Windows NT 10.0; Win64; x64)
* **IDE :** IntelliJ IDEA Community Edition 2023.1
* **Java :**  OpenJDK 11

**Comment by Elena15414** [comment]
### Шаги исправления
добавила в метод yearChange в классе SavingAccount условие начисления процентов на остаток (minBalance <= balance && balance <= maxBalance)

### Скриншот
тест testRateWhenLessMinBalance
![yearChangeMinBalance](https://github.com/Elena15414/AccountBank/assets/123021392/b4f03329-b069-4e84-a3e2-fb1a36ed819e)
