### ISSUE TITLE
Отсутствуют условия проверки допустимого максимального значения баланса (maxBalance) в методе yearChange класса SavingAccount при начислении процентов #5

### ISSUE THREAD

**Issue by Alexandr-Kucherenko** [Elena15414/AccountBank#6]
# Описание
При расчете процентов в методе yearChange() класса SavingAccount отсутствует условие проверки maxBalance, в связи с чем проценты начисляются и на сумму превышающую максимальный лимит счета.
# Локация деффекта
https://github.com/Elena15414/AccountBank/blob/14170ae557771143dc5707f891cd51cbb0259e96/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88
# Шаги воспроизведения
1.Открыть код программы в IDEA, тест testRateWhenMoreMaxBalance
2.Выставить значение переменной initialBalance в 19_000 рублей
3. Выставить значение переменной maxBalance в 10_000
3.Запустить программу
4.Посмотреть на вывод в консоли

*Ожидаемый результат :* Процент будет рассчитан на сумму maxBalance 
*Фактический результат :* Программа рассчитывает сумму согласно формуле balance / 100 * rate

# Скриншот
![image](https://github.com/Elena15414/AccountBank/assets/129050393/e7b03def-a1d9-46e1-b155-6d065e0a6232)
#  Окружение
* **Операционная система :** Mozilla/5.0 (Windows NT 10.0; Win64; x64)
*  **IDE :**  IntelliJ IDEA Community Edition 2023.1
*  **Java :** OpenJDK 11

**Comment by Elena15414** [comment]
### Шаги выполнения
добавила в метод yearChange в классе SavingAccount условие начисления процентов на остаток (balance <= maxBalance)

### Скриншот
![yearChangeMaxBalance](https://github.com/Elena15414/AccountBank/assets/123021392/5fea0e65-8e02-4537-9024-3ed50368c7cd)
